### ISSUE TITLE
Add autoupdate

### ISSUE THREAD

**Issue by cfjedimaster** [apache/openwhisk-vscode#19]
It would be epic if VSC could automatically push up code on a Save operation.

**Comment by triceam** [comment]
from slack: 

```i would do one of the command prompts when setting up the association
and associate x file with y action
and make it so you can come back later and edit```

**Comment by cfjedimaster** [comment]
I'd add that I'd also be ok with forcing you to use the same file name as the action - minus .js of course. So it would only work if foo.js mapped to an action named foo.

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
