### ISSUE TITLE
When invoking, remember last selection per file

### ISSUE THREAD

**Issue by cfjedimaster** [apache/openwhisk-vscode#20]
When I run wsk action invoke, it would be nice if it could remember the action I selected last time for a particular file.

I know we've spoken in Slack about being able to 'auto update' on file save and needing a way to associate file X with action Y, but for now, a simple in memory object storing filename/action would be cool. 

(This is assuming the list ui Code presents allows you to pre-select.)

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
