### ISSUE TITLE
Cannot connect to OW deployment

### ISSUE THREAD

**Issue by michaelmarth** [apache/openwhisk-vscode#22]
Trying to run the extension on a Mac and connect to my own OW deployment.
After configuring as described within VSCode (using the command shell and setting apihost and auth) I get in the terminal when I try to e.g. execute `wsk action list`:
```
$ wsk action list
Error: Error encountered calling OpenWhisk: Error: getaddrinfo ENOTFOUND http http:443 
```
`wsk` is correctly configured on the command line and works fine.
I also tried to use the terminal window within VSCode and ran:
```
wsk property set --apihost http://(hostname).adobe.io --auth (token)
wsk action list
```
Works well within VSCode.

I also compared my files ~/.wskprops and ~/.openwhisk/vscode-config.json. They seem the same.
Only thing that stands out to me is the erreor message mentioning "443". I have configured the host as *http*, not *https* (in both cases). But the server responds on http as well and also have tried to configure VSCode for https.
Any logs or other info I could share with this issue?

**Comment by michaelmarth** [comment]
Hmm, colleague of mine got it working on his machine - obviously a local problem for me. Feel free to either close this or let me know if I can supply any debug info in case you want to pursue it. Thx!

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
