### ISSUE TITLE
Unable to create or update action

### ISSUE THREAD

**Issue by ashleydp** [apache/openwhisk-vscode#26]
- Git revision: git version 2.13.6 (Apple Git-96)
- OS Version: MacOS - 10.12.6

Steps to Reproduce:

1. wsk action init
2. wsk action create <provide action name>
<img width="927" alt="screen shot 2017-11-22 at 2 11 33 pm" src="https://user-images.githubusercontent.com/2753974/33145612-163b331a-cf8f-11e7-8b2f-9aa275cdd323.png">

3. The same issue occurs when using wsk action update
Screencaps: (use [recordit](http://recordit.co) or something comparable)

Note that all the other commands are working fine. Also wsk properties have been set for api, namespace and auth.

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
