### ISSUE TITLE
read wsk properties from cli config

### ISSUE THREAD

**Issue by triceam** [apache/openwhisk-vscode#3]
Read properties from CLI config ~/.wskprops

**Comment by michaelmarth** [comment]
FWIW: that'd be awesome 👍

**Comment by cfjedimaster** [comment]
You could execute `wsk property get` and parse the result.

**Comment by rabbah** [comment]
i suggest also supporting `WSK_CONFIG_FILE` from the environment.

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
