### ISSUE TITLE
 Error encountered calling OpenWhisk: Error: certificate has expired

### ISSUE THREAD

**Issue by dfederschmidt** [apache/openwhisk-vscode#6]
- Git revision:

```
git version 2.8.3
```
- OS Version:

```
Linux dani-tp 3.19.0-59-generic #66~14.04.1-Ubuntu SMP Fri May 13 17:27:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- Remarks:
  - I'm creating this action on a custom openwhisk environment, not on bluewhisk
  - creating the action from the CLI works
  - Running `wsk property get` from the editor yields
  
  ```
  apiHost            <myhost>
  namespace          guest
  auth               <myauth>
  ```
  
  All of the above seem to be set correctly.

Steps to Reproduce:
1. Select `wsk action create with a simple js action open

Screencaps: 
![image](https://cloud.githubusercontent.com/assets/2430239/16168074/b978e3e2-34fe-11e6-9107-b692614d2d11.png)

Error: 

```
ERROR: Error: Error encountered calling OpenWhisk: Error: certificate has expired
```

This issue seems to be related to the whisk js sdk, not sure where the error is generated though so I open an issue here because it's where I observed it.

**Comment by triceam** [comment]
Ok, thanks.  I have not seen this before.  Actually, I have only tested against OpenWhisk staging and prod environments.   Was this a local instance running inside of the vagrant image?

**Comment by danielfederschmidt** [comment]
This was against an OpenWhisk instance hosted on multiple remote VM's
Am 24.06.2016 5:49 nachm. schrieb "Andrew Trice" <notifications@github.com>:

**Comment by triceam** [comment]
Any chance you can share access so i can try to reproduce it?  Ping me on slack.

**Comment by danielfederschmidt** [comment]
Will do!

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
